name: PR Lint

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  pr-lint:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: morrisoncole/pr-lint-action@v1.7.0
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          title-regex: '^(fix|feat|chore|docs|style|refactor|perf|test|ci|build|breaking-change|revert):\s(?:\D)[\w\d\s\-\.\,\_]+$'
          on-failed-regex-fail-action: true
          on-failed-regex-create-review: true
          on-failed-regex-comment: 'PR title must match: `%regex%`!'
