on:
  push:
    branches:
      - main

jobs:
  build-web-release:
    runs-on: ubuntu-latest
    environment: alpha
    name: Build and push Web docker image for release

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        id: build
        env:
          ECR_REGISTRY: ${{ vars.ECR_REGISTRY }}
          ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
        run: |
          # Build a docker container and push it to ECR 
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $ECR_REGISTRY
          docker build -t keyshade/keyshade-web:alpha-${GITHUB_SHA::6} $ECR_REGISTRY/$ECR_REPOSITORY:latest -f ./apps/web/Dockerfile .
          echo "Pushing image to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          echo "name=image::$ECR_REGISTRY/$ECR_REPOSITORY:latest" >> $GITHUB_OUTPUT

      - name: Force re-deploy task in service
        id: force-redeploy
        run: |
          aws ecs update-service --cluster shaer-stage-cluster --service backend-stage-service --force-new-deployment
