on:
  push:
    paths: ['apps/web/**', '.github/workflows/web.yaml']
  pull_request:
    paths: ['apps/web/**']

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Install packages
        run: |
          pnpm i

      - name: Lint
        run: |
          pnpm run lint:web

      - name: Test
        run: |
          pnpm run test:web

  deploy:
    needs: validate
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Deploy

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Install packages
        run: |
          pnpm i

      - name: Build and deploy
        run: |
          pnpm install --global vercel
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
